### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by cbmarcum** [cbmarcum/skeletal-gradle-plugin#5]
issue for updating documentation

**Comment by cbmarcum** [comment]
move usage content to asciidoc and add build info to readme

**Comment by danielfcastro** [comment]
Please consider on that documentation update addressing that when run gradlew publishToMavenLocal I get an error like below.

gradlew publishToMavenLocal

> Configure project :
Signing plugin detected. Will automatically sign the published artifacts.

> Task :signPluginMavenPublication FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':signPluginMavenPublication'.
> Cannot perform signing task ':signPluginMavenPublication' because it has no configured signatory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
9 actionable tasks: 3 executed, 6 up-to-date

**Comment by cbmarcum** [comment]
@danielfcastro Thanks for the suggestion and your interest in the project.
